# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: khan.reh@northeastern.edu
author_name: Rehan Khan
cloud_provider: none
contract_name: lending_contract
preset_name: production
project_name: lending-platform

